"""Canonical subjective-effect hierarchy.

Definitions intentionally live in ``effect_ontology.definitions`` so this file
remains a compact, reviewable source of truth for labels, domain membership,
ordering, and direct rollup relationships.
"""

CONTROLLED_EFFECT_ONTOLOGY = {
    "visual": {
        "visual distortions": "visual distortions",
        "patterning": "visual distortions",
        "texture rippling": "visual distortions",
        "surface breathing": "visual distortions",
        "visual liquefaction": "visual distortions",
        "warping": "visual distortions",
        "morphing": "visual distortions",
        "drifting": "visual distortions",
        "shimmering": "visual distortions",
        "visual vibration": "visual distortions",
        "fractal imagery": "visual distortions",
        "geometric imagery": "visual distortions",
        "visual imagery": "visual distortions",
        "simple visual hallucination": "visual distortions",
        "complex visual hallucination": "visual distortions",
        "visual trails": "visual distortions",
        "afterimages": "visual distortions",
        "motion exaggeration": "visual distortions",
        "color saturation enhancement": "visual distortions",
        "brightness enhancement": "visual distortions",
        "contrast enhancement": "visual distortions",
        "visual acuity enhancement": "visual distortions",
        "visual snow": "visual distortions",
        "pattern recognition enhancement": "visual distortions",
        "pareidolia": "visual distortions",

        "size distortion": "visual distortions",
        "distance distortion": "visual distortions",
        "depth distortion": "visual distortions",
        "foreshortening distortion": "visual distortions",
        "perspective distortion": "visual distortions",
        "scene replacement": "visual distortions",
        "environmental transfiguration": "visual distortions",
        "zooming": "visual distortions",
        "visual fragmentation": "visual distortions",
        "visual multiplicity": "visual distortions",
        "blurred vision": "visual distortions",
        "field narrowing": "visual distortions",
        "field widening": "visual distortions",
        "light haloing": "visual distortions",
        "color tinting": "visual distortions",
        "color suppression": "visual distortions",
        "visual motion discontinuity": "visual distortions",
        "object animation": "visual distortions",
        "photophobia": "visual distortions",
        "visual haziness": "visual distortions",
        "visual recursion": "visual distortions",
        "textual instability": "visual distortions",
    },
    "auditory": {
        "auditory distortions": "auditory distortions",
        "auditory enhancement": "auditory distortions",
        "sound clarity enhancement": "auditory distortions",
        "sound amplification": "auditory distortions",
        "sound dampening": "auditory distortions",
        "echoing": "auditory distortions",
        "reverberation": "auditory distortions",
        "pitch distortion": "auditory distortions",
        "tempo distortion": "auditory distortions",
        "sound duration distortion": "auditory distortions",
        "timbre distortion": "auditory distortions",
        "auditory imagery": "auditory distortions",
        "auditory hallucination": "auditory distortions",
        "sound localization distortion": "auditory distortions",
        "auditory looping": "auditory distortions",
        "auditory pareidolia": "auditory distortions",
    },
    "olfactory": {
        "olfactory change": "olfactory change",
        "olfactory enhancement": "olfactory change",
        "olfactory suppression": "olfactory change",
        "olfactory hallucination": "olfactory change",
        "olfactory distortion": "olfactory change",
    },
    "gustatory": {
        "gustatory change": "gustatory change",
        "taste enhancement": "gustatory change",
        "taste suppression": "gustatory change",
        "gustatory hallucination": "gustatory change",
        "taste distortion": "gustatory change",
    },
    "synesthetic": {
        "synesthetic change": "synesthetic change",
        "synesthesia": "synesthetic change",
    },
    "vestibular": {
        "vestibular change": "vestibular change",
        "vertigo": "vestibular change",
        "illusory acceleration": "vestibular change",
        "illusory levitation": "vestibular change",
        "illusory falling": "vestibular change",
        "illusory self-motion": "vestibular change",
        "gravitational distortion": "vestibular change",
    },
    "interoceptive": {
        "body awareness change": "body awareness change",
        "proprioceptive distortion": "body awareness change",
        "interoceptive amplification": "body awareness change",
        "interoceptive attenuation": "body awareness change",
        "visceral distortion": "body awareness change",
        "cardiac awareness": "body awareness change",
        "respiratory awareness": "body awareness change",
    },
    "somatic": {
        "body load": "body load",
        "somatic heaviness": "body load",
        "somatic lightness": "body load",
        "stimulation": "body load",
        "sedation": "body load",
        "physical energy": "body load",
        "fatigue": "body load",
        "restlessness": "body load",
        "agitation": "body load",
        "tremor": "body load",
        "muscle tension": "body load",
        "muscle relaxation": "body load",
        "jaw tension": "body load",
        "bruxism": "body load",
        "tingling": "body load",
        "pins and needles": "body load",
        "numbness": "body load",
        "warmth": "body load",
        "coldness": "body load",
        "temperature fluctuation": "body load",
        "flushing": "body load",
        "chills": "body load",
        "goosebumps": "body load",
        "pressure sensation": "body load",
        "tightness": "body load",
        "lightheadedness": "body load",
        "dizziness": "body load",
        "weakness": "body load",
        "bodily buzzing": "body load",
        "electric sensations": "body load",
        "physical comfort": "body load",
        "physical discomfort": "body load",
        "pain": "body load",
        "pain relief": "body load",
        "pain amplification": "body load",
        "itching": "body load",
        "bodily pleasure": "body load",
        "palpitations": "body load",
        "dyspnea": "body load",
        "malaise": "body load",
        "thirst": "body load",
        "urinary urgency": "body load",
        "urinary retention": "body load",
        "perspiration change": "body load",
        "formication": "body load",
    },
    "motor": {
        "motor change": "motor change",
        "incoordination": "motor change",
        "impaired balance": "motor change",
        "impaired fine motor control": "motor change",
        "akathisia": "motor change",
        "compulsive movement": "motor change",
        "stillness": "motor change",
        "immobility": "motor change",
        "muscle twitching": "motor change",
        "jerking": "motor change",
        "nystagmus": "motor change",
        "dysarthria": "motor change",
        "catalepsy": "motor change",
    },
    "gastrointestinal": {
        "gastrointestinal effects": "gastrointestinal effects",
        "nausea": "gastrointestinal effects",
        "vomiting": "gastrointestinal effects",
        "stomach discomfort": "gastrointestinal effects",
        "cramping": "gastrointestinal effects",
        "bloating": "gastrointestinal effects",
        "loss of appetite": "gastrointestinal effects",
        "increased appetite": "gastrointestinal effects",
        "dry mouth": "gastrointestinal effects",
        "salivation": "gastrointestinal effects",
        "difficulty swallowing": "gastrointestinal effects",
        "diarrhea": "gastrointestinal effects",
        "constipation": "gastrointestinal effects",
        "bowel urgency": "gastrointestinal effects",
        "acid reflux": "gastrointestinal effects",
        "flatulence": "gastrointestinal effects",
        "hiccups": "gastrointestinal effects",
    },
    "emotional": {
        "emotional change": "emotional change",
        "euphoria": "emotional change",
        "joy": "emotional change",
        "contentment": "emotional change",
        "emotional warmth": "emotional change",
        "affection": "emotional change",
        "love": "emotional change",
        "compassion": "emotional change",
        "gratitude": "emotional change",
        "relief": "emotional change",
        "calmness": "emotional change",
        "inner peace": "emotional change",
        "anxiety": "emotional change",
        "apprehension": "emotional change",
        "fear": "emotional change",
        "panic": "emotional change",
        "impending doom": "emotional change",
        "paranoia": "emotional change",
        "irritability": "emotional change",
        "anger": "emotional change",
        "frustration": "emotional change",
        "sadness": "emotional change",
        "grief": "emotional change",
        "emotional lability": "emotional change",
        "emotional blunting": "emotional change",
        "emotional sensitivity": "emotional change",
        "awe": "emotional change",
        "wonder": "emotional change",
        "surprise": "emotional change",
        "giddiness": "emotional change",
        "emotional catharsis": "emotional change",
        "helplessness": "emotional change",
        "suspiciousness": "emotional change",
        "anxiety relief": "emotional change",
        "fear relief": "emotional change",
        "nostalgia": "emotional change",
        "shame": "emotional change",
        "guilt": "emotional change",
        "embarrassment": "emotional change",
        "disgust": "emotional change",
        "contempt": "emotional change",
        "dysphoria": "emotional change",
        "anhedonia": "emotional change",
        "apathy": "emotional change",
        "hopelessness": "emotional change",
        "emotional overwhelm": "emotional change",
        "excitement": "emotional change",
        "self-confidence elevation": "emotional change",
        "self-esteem elevation": "emotional change",
        "motivation enhancement": "emotional change",
        "motivation suppression": "emotional change",
        "boredom": "emotional change",
        "curiosity enhancement": "emotional change",
        "self-esteem suppression": "emotional change",
        "patience enhancement": "emotional change",
        "patience suppression": "emotional change",
        "craving": "emotional change",
        "loneliness": "emotional change",
        "dread": "emotional change",
        "acceptance": "emotional change",
        "vulnerability": "emotional change",
        "amusement": "emotional change",
        "envy": "emotional change",
        "jealousy": "emotional change",
        "resentment": "emotional change",
        "regret": "emotional change",
        "forgiveness": "emotional change",
        "humility": "emotional change",
        "self-compassion enhancement": "emotional change",
        "aesthetic appreciation": "emotional change",
        "optimism enhancement": "emotional change",
        "pessimism": "emotional change",
        "playfulness": "emotional change",
        "sentimentality": "emotional change",
        "tenderness": "emotional change",
        "sense of safety": "emotional change",
        "self-criticism enhancement": "emotional change",
        "closure": "emotional change",
        "defensiveness": "emotional change",
        "self-acceptance": "emotional change",
        "indifference": "emotional change",
        "melancholy": "emotional change",
        "homesickness": "emotional change",
        "relational longing": "emotional change",
        "anticipatory pleasure": "emotional change",
        "savoring": "emotional change",
        "emotional exhaustion": "emotional change",
        "task aversion": "emotional change",
        "moral elevation": "emotional change",
        "pride": "emotional change",
        "disappointment": "emotional change",
        "vindictiveness": "emotional change",
        "embitterment": "emotional change",
        "admiration": "emotional change",
        "compersion": "emotional change",
        "schadenfreude": "emotional change",
        "ambivalence": "emotional change",
        "emotional incongruence": "emotional change",
        "determination": "emotional change",
        "courage": "emotional change",
    },
    "cognitive": {
        "cognitive change": "cognitive change",
        "confusion": "cognitive change",
        "mental clarity": "cognitive change",
        "foggy thinking": "cognitive change",
        "racing thoughts": "cognitive change",
        "thought pressure": "cognitive change",
        "thought slowing": "cognitive change",
        "thought looping": "cognitive change",
        "thought interference": "cognitive change",
        "distractibility": "cognitive change",
        "rumination": "cognitive change",
        "obsessive thinking": "cognitive change",
        "memory impairment": "cognitive change",
        "memory enhancement": "cognitive change",
        "language impairment": "cognitive change",
        "speech fluency enhancement": "cognitive change",
        "analysis enhancement": "cognitive change",
        "introspection enhancement": "cognitive change",
        "novel associations": "cognitive change",
        "conceptual thinking": "cognitive change",
        "suggestibility": "cognitive change",
        "reduced inhibition": "cognitive change",
        "increased focus": "cognitive change",
        "decreased focus": "cognitive change",
        "attentional absorption": "cognitive change",
        "thought disorganization": "cognitive change",
        "mind blanking": "cognitive change",
        "delusional thinking": "cognitive change",
        "ideas of reference": "cognitive change",
        "grandiosity": "cognitive change",
        "hypervigilance": "cognitive change",
        "compulsive meaning-making": "cognitive change",
        "decision paralysis": "cognitive change",
        "internal cognitive split": "cognitive change",
        "meta-awareness of irrationality": "cognitive change",
        "double bookkeeping": "cognitive change",
        "déjà vu": "cognitive change",
        "jamais vu": "cognitive change",
        "creativity enhancement": "cognitive change",
        "memory resurfacing": "cognitive change",
        "amnesia": "cognitive change",
        "ideational pleasure": "cognitive change",
        "internal monologue suppression": "cognitive change",
        "intrusive thoughts": "cognitive change",
        "catastrophic thinking": "cognitive change",
        "confabulation": "cognitive change",
        "thought ownership loss": "cognitive change",
        "thought insertion": "cognitive change",
        "thought broadcasting": "cognitive change",
        "thought echo": "cognitive change",
        "inner speech externalization": "cognitive change",
        "impulsivity": "cognitive change",
        "risk perception suppression": "cognitive change",
        "mental imagery enhancement": "cognitive change",
        "thought blocking": "cognitive change",
        "thought fading": "cognitive change",
        "source monitoring impairment": "cognitive change",
        "magical thinking": "cognitive change",
        "perseveration": "cognitive change",
        "cognitive rigidity": "cognitive change",
        "metacognitive impairment": "cognitive change",
        "cognitive decentering": "cognitive change",
        "hyperreflexivity": "cognitive change",
        "semantic satiation": "cognitive change",
        "salience enhancement": "cognitive change",
        "attentional narrowing": "cognitive change",
        "planning impairment": "cognitive change",
        "mental imagery suppression": "cognitive change",
        "reality testing impairment": "cognitive change",
        "orientation impairment": "cognitive change",
        "perplexity": "cognitive change",
        "psychological insight": "cognitive change",
        "volitional control impairment": "cognitive change",
        "emotion identification difficulty": "cognitive change",
        "dreamlike cognition": "cognitive change",
        "counterfactual thinking": "cognitive change",
        "life review": "cognitive change",
        "flight of ideas": "cognitive change",
        "hypergraphia": "cognitive change",
        "belief flexibility enhancement": "cognitive change",
        "working memory impairment": "cognitive change",
        "prospective memory impairment": "cognitive change",
        "task switching impairment": "cognitive change",
        "reading comprehension impairment": "cognitive change",
        "numeracy impairment": "cognitive change",
        "metaphorical thinking enhancement": "cognitive change",
        "absurdity perception": "cognitive change",
        "skepticism enhancement": "cognitive change",
        "certainty seeking": "cognitive change",
        "predictive thinking enhancement": "cognitive change",
        "cognitive effort amplification": "cognitive change",
        "cognitive effort reduction": "cognitive change",
        "literal thinking enhancement": "cognitive change",
        "abstraction difficulty": "cognitive change",
    },
    "temporal": {
        "time distortion": "time distortion",
        "time dilation": "time distortion",
        "time contraction": "time distortion",
        "timelessness": "time distortion",
        "time fragmentation": "time distortion",
        "looping sense of time": "time distortion",
        "time reversal": "time distortion",
        "time stoppage": "time distortion",
        "temporal simultaneity": "time distortion",
        "temporal ordering disruption": "time distortion",
    },
    "spatial": {
        "spatial change": "spatial change",
        "spatial scale distortion": "spatial change",
        "spatial boundlessness": "spatial change",
        "spacelessness": "spatial change",
        "perspectival dislocation": "spatial change",
    },
    "world-experience": {
        "world-experience change": "world-experience change",
        "uncanniness": "world-experience change",
        "atmospheric portent": "world-experience change",
        "environmental vitality loss": "world-experience change",
        "perceptual meaning loss": "world-experience change",
        "perceptual freshness": "world-experience change",
        "hyperfamiliarity": "world-experience change",
    },
    "selfhood": {
        "selfhood change": "selfhood change",
        "dissociation": "selfhood change",
        "depersonalization": "selfhood change",
        "derealization": "selfhood change",
        "ego softening": "selfhood change",
        "ego dissolution": "selfhood change",
        "ego inflation": "selfhood change",
        "loss of self-other boundary": "selfhood change",
        "identity confusion": "selfhood change",
        "observer perspective": "selfhood change",
        "disembodiment": "selfhood change",
        "unity experience": "selfhood change",
        "theriomorphosis": "selfhood change",
        "agency loss": "selfhood change",
        "action automaticity": "selfhood change",
        "external control experience": "selfhood change",
        "affect ownership loss": "selfhood change",
        "identity fluidity": "selfhood change",
        "self-multiplication": "selfhood change",
        "inanimate self-transformation": "selfhood change",
        "autoscopy": "selfhood change",
        "heautoscopy": "selfhood change",
        "felt death": "selfhood change",
        "body ownership distortion": "selfhood change",
        "mirror self-recognition disturbance": "selfhood change",
        "age regression": "selfhood change",
        "personal continuity disruption": "selfhood change",
        "body image distortion": "selfhood change",
        "gender identity shift": "selfhood change",
        "name alienation": "selfhood change",
        "self-diminishment": "selfhood change",
        "diminished self-presence": "selfhood change",
        "authenticity enhancement": "selfhood change",
        "role identification": "selfhood change",
        "social mask suppression": "selfhood change",
        "agency enhancement": "selfhood change",
        "impostor feeling": "selfhood change",
    },
    "spiritual": {
        "spiritual experience": "spiritual experience",
        "sacredness": "spiritual experience",
        "revelatory insight": "spiritual experience",
        "existential insight": "spiritual experience",
        "cosmic significance": "spiritual experience",
        "sensed presence": "spiritual experience",
        "interconnectedness": "spiritual experience",
        "spiritual rebirth": "spiritual experience",
        "noetic certainty": "spiritual experience",
        "ineffability": "spiritual experience",
        "pure awareness": "spiritual experience",
        "coincident opposites": "spiritual experience",
        "synchronicity perception": "spiritual experience",
        "animistic attribution": "spiritual experience",
        "fatedness": "spiritual experience",
    },
    "social": {
        "social change": "social change",
        "sociability enhancement": "social change",
        "talkativeness": "social change",
        "empathy enhancement": "social change",
        "social openness": "social change",
        "social confidence": "social change",
        "social anxiety": "social change",
        "withdrawal": "social change",
        "feeling understood": "social change",
        "feeling connected": "social change",
        "communitas": "social change",
        "feeling alienated": "social change",
        "trust enhancement": "social change",
        "trust suppression": "social change",
        "empathy suppression": "social change",
        "rejection sensitivity": "social change",
        "intimacy enhancement": "social change",
        "altruism enhancement": "social change",
        "belongingness enhancement": "social change",
        "attachment enhancement": "social change",
        "disclosure urge": "social change",
        "approval seeking": "social change",
        "conflict aversion": "social change",
        "protectiveness": "social change",
        "dominance feelings": "social change",
        "submissiveness": "social change",
        "social comparison enhancement": "social change",
        "cooperation enhancement": "social change",
        "assertiveness enhancement": "social change",
        "boundary setting enhancement": "social change",
        "conformity enhancement": "social change",
        "contrarianism": "social change",
        "perspective-taking enhancement": "social change",
        "perspective-taking impairment": "social change",
        "competitiveness": "social change",
        "obedience enhancement": "social change",
        "privacy concern suppression": "social change",
        "impression management enhancement": "social change",
        "privacy concern enhancement": "social change",
        "transparency feeling": "social change",
    },
    "tactile": {
        "tactile change": "tactile change",
        "tactile amplification": "tactile change",
        "tactile attenuation": "tactile change",
        "tactile distortion": "tactile change",
        "skin sensitivity": "tactile change",
        "tactile localization distortion": "tactile change",
        "tactile recognition impairment": "tactile change",
        "tactile hallucination": "tactile change",
    },
    "sexual": {
        "sexual change": "sexual change",
        "increased libido": "sexual change",
        "decreased libido": "sexual change",
        "increased sensuality": "sexual change",
        "sexual arousal enhancement": "sexual change",
        "sexual arousal suppression": "sexual change",
        "sexual dysfunction": "sexual change",
        "orgasm enhancement": "sexual change",
        "orgasm delay": "sexual change",
        "anorgasmia": "sexual change",
        "spontaneous orgasm": "sexual change",
    },
    "sleep": {
        "sleep disturbance": "sleep disturbance",
        "insomnia": "sleep disturbance",
        "difficulty falling asleep": "sleep disturbance",
        "sleep fragmentation": "sleep disturbance",
        "vivid dreams": "sleep disturbance",
        "lucid dreams": "sleep disturbance",
        "dream recall enhancement": "sleep disturbance",
        "drowsiness": "sleep disturbance",
        "hypnagogia": "sleep disturbance",
        "hypnopompia": "sleep disturbance",
        "sleep paralysis": "sleep disturbance",
        "false awakening": "sleep disturbance",
        "dream-reality confusion": "sleep disturbance",
        "nightmares": "sleep disturbance",
        "hypersomnia": "sleep disturbance",
    },
}
